repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=100']
    -   id: name-tests-test
    -   id: flake8
        args: ['--max-line-length=120', '--ignore=E203,W503']
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
        language_version: python3.8
-   repo: https://github.com/Lucas-C/pre-commit-hooks-bandit
    rev: v1.0.4
    hooks:
    -   id: python-bandit-vulnerability-check
        args: ['-lll', '--recursive', '-x', 'tests']
        file: .py$
